## How to perform singular value decomposition on sparse matrix

In [1]:
import timeit

import scipy
import scipy.sparse as ss
import numpy as np

https://jakevdp.github.io/blog/2012/12/19/sparse-svds-in-python/

https://www.zhihu.com/question/56467072

In [3]:
N = 2 ** np.arange(3, 12)

In [4]:
N

array([   8,   16,   32,   64,  128,  256,  512, 1024, 2048])

In [11]:
N1_N2_f = np.broadcast(N,N, 0.6)

In [12]:
N1_N2_f.shape

(9,)

In [13]:
for (N1, N2, f) in N1_N2_f:
    print(N1, N2, f)

8 8 0.6
16 16 0.6
32 32 0.6
64 64 0.6
128 128 0.6
256 256 0.6
512 512 0.6
1024 1024 0.6
2048 2048 0.6


In [15]:
np.arange(6000, 12000, 1000)

array([ 6000,  7000,  8000,  9000, 10000, 11000])

In [19]:
np.random.normal(0, 1, (10, 2))

array([[-1.69786837,  1.40683476],
       [-0.21456374,  0.01685531],
       [ 1.85255608, -0.9584743 ],
       [ 0.2097405 ,  0.20164185],
       [-1.46951761,  0.86073821],
       [ 0.00336579,  0.15714732],
       [ 1.77479794, -0.91660779],
       [-0.6145696 ,  0.67247255],
       [-0.01893982,  0.29894764],
       [ 0.63287178,  0.89723576]])

In [22]:
np.random.RandomState(1).rand(2,5)

array([[4.17022005e-01, 7.20324493e-01, 1.14374817e-04, 3.02332573e-01,
        1.46755891e-01],
       [9.23385948e-02, 1.86260211e-01, 3.45560727e-01, 3.96767474e-01,
        5.38816734e-01]])

In [23]:
np.random.rand(2,5)

array([[0.07087962, 0.99726584, 0.25292818, 0.55440368, 0.10746496],
       [0.67273734, 0.75051153, 0.54474621, 0.32442689, 0.8966914 ]])

In [24]:
np.random.normal(0,1,(2,5))

array([[-0.46507344, -0.20170789, -0.46588246,  2.25072115,  1.03911254],
       [-0.07297782, -0.59013497,  0.38661011,  1.75128747, -0.48029361]])

In [2]:
timeit.timeit('''
ss.lobpcg()
''',
number=5
)

0
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2
1
2


405.048497900003

<module 'scipy.sparse' from '/opt/conda/lib/python3.8/site-packages/scipy/sparse/__init__.py'>

In [3]:
timeit.timeit('''
import sparse_svd as ss
ss.arpack()
''',
number=5
)

AttributeError: module 'sparse_svd' has no attribute 'arpack'

In [2]:
cell_num = np.arange(6000, 16000, 1000)
gene_num = np.arange(20000, 120000, 10000)
rng = np.random.RandomState(0)

In [ ]:
for i, j in zip(cell_num, gene_num):
    M = rng.normal(0, 1, (i, j))
    print(1)

1
1
1
1
